### ISSUE TITLE
Binary Heap Implementation

### ISSUE THREAD

**Issue by trevmoy** [SP24-212/Edstem-Tracker#2]
## Creating Binary Heap

You can refer to these (or any additional) resources for binary heaps:
- [GeeksforGeeks](https://www.geeksforgeeks.org/binary-heap/)
- [Wikipedia](https://en.wikipedia.org/wiki/Binary_heap)
- [Brilliant](https://brilliant.org/wiki/binary-heap/)
- [Visualizer](https://visualgo.net/en/heap?slide=1-4)
- [Takeuforward](https://takeuforward.org/heap/binary-heap-implementation/)

**Comment by lnero18** [comment]
Beautiful guide and sources - Thx tevor.
